### ISSUE TITLE
How's programming.

### ISSUE THREAD

**Issue by mjhejazi** [deadsy/grbl_stm32f4#5]
hi
The program would be open to what application programming?
I'm working Keil

**Comment by mjhejazi** [comment]
Is this code with software opens TrueSTUDIO?

**Comment by andywang1005** [comment]
Hi
i am also working on Keil. I have the same question...
did you find a way to do that?
Thanks in advance

**Comment by mjhejazi** [comment]
Hi 
No, I did not find.
Regards
MJHejazi.

**Comment by deadsy** [comment]
I don't have or use Keil. I use the gcc tools running on Linux. It wouldn't be that hard to have work with another c compiler - it's just work.
