### ISSUE TITLE
Porting to F469

### ISSUE THREAD

**Issue by mopplayer** [deadsy/grbl_stm32f4#6]
I want to port to STM32F469-DIS
Is there a good way to get started?
It seems that to modify PIN Map, Right?
Thanks to your help.

**Comment by deadsy** [comment]
Yes - you'll have to remap the IO to whatever the available pins are on your board. The core drivers should be OK since you are on an ST chip and the peripherals don't change much, but you'll have to make sure the base addresses are ok.
