### ISSUE TITLE
G Code 

### ISSUE THREAD

**Issue by Emre-ee** [deadsy/grbl_stm32f4#7]
Hi,
I am using the grbl library. In addition, I have added it in the encoder and I can compare the position information from the encoder with the position information from the stepper motor. However, if the motor has not reached the desired position, I want to move it in code myself. I know how to move from serial terminal. How do I write the move code? Since I am using Arduino, I could not fully understand the operation of the code because I could not debug the code. Can you please help?

**Comment by deadsy** [comment]
The motor driver portion of the grbl code is written to use steppers which do not have encoders. ie - the expectation is that the stepper will in fact move the required numbers of steps. In your case you have an encoder as a feedback path so you have to rewrite the motor driver portions to use that in some sort of feedback loop. I'm familiar with PID control but not so much with steppers + encoders. I assume some google searchs would you let you know good techniqies for controlling steppers with encoder feedback. Then you just have to write the driver :-)

**Comment by Emre-ee** [comment]
Ok, thank you so much.
